# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f5cf7879addabd14fa314e0bc1aced10b4a6f134522d99b33847ccea1ed45add8b5fb2f837181b72faf18bad365820a6dd29b5bdf7f70656a1419d480cea67d

test:
  secret_key_base: 6021bc9b42b15999589c7b7759abf3d2c5d491c25d9dfe4fa9608075fd0e9ea8798708126e2a5b38d55222695e13de14f8f648e9d2b47fef031b15d821960e9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
